version: '3'

services:
  <% if (dbType === 'PostgreSQL') { %>
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: <%= baseName %>
    networks:
      - my-network
  <% } %>
  <% if (dbType === 'MySQL') { %>
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: <%= baseName %>
    networks:
      - my-network
  <% } %>
  <% if (dbType === 'MongoDB') { %>
  mongo:
    image: mongo
    networks:
      - my-network
  <% } %>
  <%= baseName %>:
    image: <%= baseName %>
    networks:
      - my-network
    environment:
      <% if (dbType === 'PostgreSQL') { %>
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/<%= baseName %>
      <% } else if (dbType === 'MySQL') { %>
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/<%= baseName %>
      <% } else if (dbType === 'MongoDB') { %>
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/<%= baseName %>
      <% } %>

networks:
  my-network:
    driver: bridge
